<script setup lang="ts">
import type { FamilyMemberNode } from "~/types/family";
import { LOGO_BASE64 } from '~/constants/logo';

defineProps<{
  treeData: FamilyMemberNode[];
  maxGen: number;
  count: number;
  activeBaniName?: string;
  viewType: "chart" | "table";
}>();

const logoBase64 = ref("");

// Fungsi untuk konversi image ke Base64 agar terbaca saat export di HP
const loadLogoAsBase64 = async () => {
  try {
    // Gunakan cache: 'no-cache' agar Safari benar-benar mengambil data segar
    const response = await fetch("/logo-green.webp", { cache: "no-cache" });
    const blob = await response.blob();
    const reader = new FileReader();
    reader.onloadend = () => {
      logoBase64.value = reader.result as string;
    };
    reader.readAsDataURL(blob);
  } catch (e) {
    console.error("Gagal load logo:", e);
  }
};

onMounted(() => {
  loadLogoAsBase64();
});

const currentDate = new Date().toLocaleDateString("id-ID", {
  year: "numeric",
  month: "long",
  day: "numeric"
});
</script>

<template>
  <!-- Lebar dipaksa minimal 1600px agar layout selalu landscape -->
  <div class="bg-white p-16 w-[1800px]">
    <!-- Header Export -->
    <div
      class="border-b-8 border-emerald-500 pb-12 mb-12 flex justify-between items-end"
    >
      <div>
        <div class="flex items-center gap-4 mb-4">
          <img :src="LOGO_BASE64" class="w-20 h-20 object-contain" />
          <!-- <div
            v-if="logoBase64"
            :style="{ backgroundImage: `url(${logoBase64})` }"
            class="w-20 h-20 bg-contain bg-no-repeat bg-center"
          ></div>

          <img src="/logo-green.webp" class="hidden" /> -->
          <p
            class="text-emerald-600 font-black uppercase text-xs tracking-[0.5em]"
          >
            Dokumen Digital Bani Nanaf
          </p>
        </div>
        <h2
          class="text-6xl font-black text-slate-900 uppercase italic tracking-tighter leading-none"
        >
          Silsilah Keluarga {{ activeBaniName }}
        </h2>
        <p
          class="text-slate-400 font-bold text-xs uppercase tracking-widest mt-4"
        >
          Keluarga Besar Bani Nanaf • Update: {{ currentDate }}
        </p>
      </div>

      <div
        class="flex gap-10 bg-slate-50 px-12 py-8 rounded-[3rem] border border-slate-100"
      >
        <div class="text-center">
          <div class="text-4xl font-black text-emerald-600 leading-none">
            {{ count }}
          </div>
          <div class="text-[10px] font-black uppercase text-slate-400 mt-2">
            Anggota
          </div>
        </div>
        <div class="h-12 w-px bg-slate-200"></div>
        <div class="text-center">
          <div class="text-4xl font-black text-emerald-600 leading-none">
            {{ maxGen }}
          </div>
          <div class="text-[10px] font-black uppercase text-slate-400 mt-2">
            Generasi
          </div>
        </div>
      </div>
    </div>

    <!-- Area Konten -->
    <div class="min-h-[600px]">
      <!-- CHART VIEW -->
      <div v-if="viewType === 'chart'">
        <!-- Header Generasi -->
        <div class="flex mb-16 border-b-2 border-slate-200 pb-10 ml-4">
          <div v-for="n in maxGen" :key="n" class="w-[280px] flex-shrink-0">
            <div class="pl-8 border-l-4 border-emerald-500">
              <span
                class="text-[10px] font-black text-slate-400 uppercase tracking-[0.4em] block mb-2"
                >Generasi</span
              >
              <div class="text-6xl font-black text-slate-600 leading-none">
                0{{ n }}
              </div>
            </div>
          </div>
        </div>
        <div class="flex flex-col ml-4">
          <FamilyNode v-for="node in treeData" :key="node.id" :node="node" />
        </div>
      </div>

      <!-- TABLE VIEW -->
      <div v-else>
        <FamilyTable
          v-for="node in treeData"
          :key="node.id"
          :rootNode="node"
          :maxGen="maxGen"
          :isAdmin="false"
        />
      </div>
    </div>

    <!-- Footer URL -->
    <div
      class="mt-20 pt-8 border-t border-slate-100 flex justify-between text-[11px] font-black uppercase text-slate-300 tracking-[0.4em]"
    >
      <span>Generated by Dokumen Digital Bani Nanaf</span>
      <span>baninanaf.syaifuddinzuhri.my.id</span>
    </div>
  </div>
</template>
